# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinicio', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonimo', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='votecounts',
            field=models.IntegerField(default=0),
        ),
    ]
