# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinicio', '0003_auto_20160412_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
