# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinicio', '0006_auto_20160418_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='votecounts',
        ),
    ]
