# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('camp2', models.CharField(max_length=200)),
            ],
        ),
    ]
