# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_base_camp2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
