# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_event_newsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='publish_date',
        ),
    ]
