# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_newsitem_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
